### ISSUE TITLE
Permission Denied on Windows

### ISSUE THREAD

**Issue by gungunfebrianza** [MarcHanin/drun#10]
Result after execute my hello world script :

PermissionDenied: Access is denied. (os error 5)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.kill ($deno$/ops/process.ts:6:3)
    at Process.kill ($deno$/process.ts:89:5)
    at Runner.run (https://deno.land/x/drun@v1.1.0/src/helpers/runner.ts:73:17)
    at async Watch.run (https://deno.land/x/drun@v1.1.0/src/commands/watch/watch.ts:78:5)
    at async main (https://deno.land/x/drun@v1.1.0/drun.ts:7:3)
    at async https://deno.land/x/drun@v1.1.0/drun.ts:12:5

**Comment by MarcHanin** [comment]
Thanks for reporting this issue.
This was fixed with https://github.com/MarcHanin/drun/pull/7 but it's not yet released.
You can install the `master` version if you want to use it now:  
`deno install --allow-read --allow-run --unstable -f https://deno.land/x/drun/drun.ts`

**Comment by gungunfebrianza** [comment]
hi marc thank you so much, looking forward to help this project to increase my productivity :)

**Comment by MarcHanin** [comment]
Hi @gungunfebrianza,
Thanks, I'm happy if this project can increase your productivity :)
It seems that your issue is now resolved, feel free to re-open it if necessary.
