### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by GiovaneRobertiTafine** [MarcHanin/drun#2]
Error when installing

Log:
```
error: TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(originSrcFilePath, dest, type);
                                              ~~~~
    at https://deno.land/std@v0.51.0/fs/copy.ts:114:47

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(originSrcFilePath, dest, type);
                                            ~~~~
    at https://deno.land/std@v0.51.0/fs/copy.ts:132:45

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(src, dest, srcFilePathType);
                                ~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.51.0/fs/ensure_symlink.ts:31:33

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(src, dest, srcFilePathType);
                              ~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.51.0/fs/ensure_symlink.ts:58:31

Found 4 errors.
```

Ambient:
Windows 10

**Comment by MarcHanin** [comment]
Thanks for reporting this error, it seems to be due to the last deno release (1.0.1).
I will update that today and create new release for Deno 1.0.1, please tell me if you have this error with deno 1.0.0

**Comment by GiovaneRobertiTafine** [comment]
Yes, with version 1.0.0, the installation proceeds normally.
Log:
`Successfully installed drun`

**Comment by MarcHanin** [comment]
It should be resolved with the latest release, I close this issue but don't hesitate to reopen it if it's not resolved for you
