### ISSUE TITLE
Argument of type 'string | URL' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by argxentakato** [MarcHanin/drun#21]
**Describe the bug**
I tried to install drun according to the README but was unable to do so with the following error.

```
Download https://deno.land/x/drun@v1.1.0/drun.ts
Download https://deno.land/x/drun@v1.1.0/src/config.ts
Download https://deno.land/x/drun@v1.1.0/src/commands_factory.ts
Download https://deno.land/x/drun@v1.1.0/src/deps.ts
Download https://deno.land/x/drun@v1.1.0/src/interfaces/types.ts
Download https://deno.land/std@v0.52.0/fs/mod.ts
Download https://deno.land/std@v0.52.0/path/mod.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/index.ts
Download https://deno.land/std@v0.52.0/fs/empty_dir.ts
Download https://deno.land/std@v0.52.0/fs/ensure_dir.ts
Download https://deno.land/std@v0.52.0/fs/ensure_file.ts
Download https://deno.land/std@v0.52.0/fs/ensure_link.ts
Download https://deno.land/std@v0.52.0/fs/ensure_symlink.ts
Download https://deno.land/std@v0.52.0/fs/exists.ts
Download https://deno.land/std@v0.52.0/fs/expand_glob.ts
Download https://deno.land/std@v0.52.0/fs/move.ts
Download https://deno.land/std@v0.52.0/fs/copy.ts
Download https://deno.land/std@v0.52.0/fs/read_file_str.ts
Download https://deno.land/std@v0.52.0/fs/write_file_str.ts
Download https://deno.land/std@v0.52.0/fs/read_json.ts
Download https://deno.land/std@v0.52.0/fs/write_json.ts
Download https://deno.land/std@v0.52.0/fs/walk.ts
Download https://deno.land/std@v0.52.0/fs/eol.ts
Download https://deno.land/std@v0.52.0/path/win32.ts
Download https://deno.land/std@v0.52.0/path/posix.ts
Download https://deno.land/std@v0.52.0/path/common.ts
Download https://deno.land/std@v0.52.0/path/separator.ts
Download https://deno.land/std@v0.52.0/path/interface.ts
Download https://deno.land/std@v0.52.0/path/glob.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/help/help.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/watch/watch.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/command.ts
Download https://deno.land/std@v0.52.0/fs/_util.ts
Download https://deno.land/std@v0.52.0/testing/asserts.ts
Download https://deno.land/std@v0.52.0/path/_constants.ts
Download https://deno.land/std@v0.52.0/path/_util.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/help/templates.ts
Download https://deno.land/x/drun@v1.1.0/src/helpers/resolve_path_array.ts
Download https://deno.land/x/drun@v1.1.0/src/helpers/runner.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/watch/validation/options_validation.ts
Download https://deno.land/x/drun@v1.1.0/src/commands/watch/templates.ts
Download https://deno.land/std@v0.52.0/path/_globrex.ts
Download https://deno.land/std@v0.52.0/fmt/colors.ts
Download https://deno.land/std@v0.52.0/testing/diff.ts
Download https://deno.land/x/drun@v1.1.0/src/errors/drun_config_validation_error.ts
Check https://deno.land/x/drun@v1.1.0/drun.ts
error TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.52.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.52.0/path/posix.ts:433:18

Found 2 errors.
```

**To Reproduce**
1. Just run `deno install --allow-read --allow-run --unstable https://deno.land/x/drun@v1.1.0/drun.ts`
2. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
  - OS: Arch Linux
  - Deno version: 1.2.0
  - Drun version: 1.1.0

**Comment by MarcHanin** [comment]
Hi @silverscat-3,
Thanks for reporting this bug.
I will fix that

**Comment by MarcHanin** [comment]
It should be fixed now on master, you can install it with:
`deno install --allow-read --allow-run --unstable https://deno.land/x/drun/drun.ts`
Don't hesitate to re-open the issue if it's not solved

**Comment by michelnovellino** [comment]
```
Warning Implicitly using latest version (v1.2.0) for https://deno.land/x/drun/drun.ts
Download https://deno.land/x/drun@v1.2.0/drun.ts
Download https://deno.land/x/drun@v1.2.0/deps.ts
Download https://deno.land/x/drun@v1.2.0/src/config.ts
Download https://deno.land/x/drun@v1.2.0/src/commands_factory.ts
Download https://deno.land/x/drun@v1.2.0/src/interfaces/types.ts
Download https://deno.land/std@v0.54.0/fs/mod.ts
Download https://deno.land/std@v0.54.0/path/mod.ts
Download https://deno.land/std@v0.54.0/log/mod.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/index.ts
Download https://deno.land/std@0.54.0/log/mod.ts
Download https://deno.land/std@0.54.0/fs/mod.ts
Download https://deno.land/std@0.54.0/path/mod.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/help/help.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/watch/watch.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/command.ts
Download https://deno.land/std@0.54.0/path/win32.ts
Download https://deno.land/std@0.54.0/path/posix.ts
Download https://deno.land/std@0.54.0/path/common.ts
Download https://deno.land/std@0.54.0/path/separator.ts
Download https://deno.land/std@0.54.0/path/interface.ts
Download https://deno.land/std@0.54.0/path/glob.ts
Download https://deno.land/std@0.54.0/log/logger.ts
Download https://deno.land/std@0.54.0/log/handlers.ts
Download https://deno.land/std@0.54.0/testing/asserts.ts
Download https://deno.land/std@0.54.0/log/levels.ts
Download https://deno.land/std@0.54.0/fs/empty_dir.ts
Download https://deno.land/std@0.54.0/fs/ensure_dir.ts
Download https://deno.land/std@0.54.0/fs/ensure_file.ts
Download https://deno.land/std@0.54.0/fs/ensure_link.ts
Download https://deno.land/std@0.54.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.54.0/fs/exists.ts
Download https://deno.land/std@0.54.0/fs/expand_glob.ts
Download https://deno.land/std@0.54.0/fs/move.ts
Download https://deno.land/std@0.54.0/fs/copy.ts
Download https://deno.land/std@0.54.0/fs/read_file_str.ts
Download https://deno.land/std@0.54.0/fs/write_file_str.ts
Download https://deno.land/std@0.54.0/fs/read_json.ts
Download https://deno.land/std@0.54.0/fs/write_json.ts
Download https://deno.land/std@0.54.0/fs/walk.ts
Download https://deno.land/std@0.54.0/fs/eol.ts
Download https://deno.land/x/drun@v1.2.0/src/helpers/resolve_path_array.ts
Download https://deno.land/x/drun@v1.2.0/src/helpers/runner.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/watch/validation/options_validation.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/watch/templates.ts
Download https://deno.land/x/drun@v1.2.0/src/commands/help/templates.ts
Download https://deno.land/std@0.54.0/path/_constants.ts
Download https://deno.land/std@0.54.0/path/_util.ts
Download https://deno.land/std@0.54.0/fmt/colors.ts
Download https://deno.land/std@0.54.0/testing/diff.ts
Download https://deno.land/std@0.54.0/path/_globrex.ts
Download https://deno.land/std@0.54.0/path/mod.ts
Download https://deno.land/std@0.54.0/fs/_util.ts
Download https://deno.land/x/drun@v1.2.0/src/errors/drun_config_validation_error.ts
Check https://deno.land/x/drun@v1.2.0/drun.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.54.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.54.0/path/posix.ts:433:18
```
it also happens to me with the previous version 1.1

**Comment by dcj9** [comment]
Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/x/dex@1.0.2/lib/deps/path/win32.ts:911:18
